export const pokemonsTypes = [
  {
    type: "normal",
    type_pt: "Normal",
    src: "src/assets/elements_images/normal.svg",
    color: "#919AA2",
  },
  {
    type: "fighting",
    type_pt: "Lutador",
    src: "src/assets/elements_images/fighting.svg",
    color: "#CE416B",
  },
  {
    type: "flying",
    type_pt: "Voador",
    src: "src/assets/elements_images/flying.svg",
    color: "#89AAE3",
  },
  {
    type: "poison",
    type_pt: "Venenoso",
    src: "src/assets/elements_images/poison.svg",
    color: "#B567CE",
  },
  {
    type: "ground",
    type_pt: "Terrestre",
    src: "src/assets/elements_images/ground.svg",
    color: "#D97845",
  },
  {
    type: "rock",
    type_pt: "Pedra",
    src: "src/assets/elements_images/rock.svg",
    color: "#C5B78C",
  },
  {
    type: "bug",
    type_pt: "Inseto",
    src: "src/assets/elements_images/bug.svg",
    color: "#91C12F",
  },
  {
    type: "ghost",
    type_pt: "Fantasma",
    src: "src/assets/elements_images/ghost.svg",
    color: "#5269AD",
  },
  {
    type: "steel",
    type_pt: "Metálico",
    src: "src/assets/elements_images/steel.svg",
    color: "#5A8EA2",
  },
  {
    type: "fire",
    type_pt: "Fogo",
    src: "src/assets/elements_images/fire.svg",
    color: "#FF9D55",
  },
  {
    type: "water",
    type_pt: "Água",
    src: "src/assets/elements_images/water.svg",
    color: "#5090D6",
  },
  {
    type: "grass",
    type_pt: "Planta",
    src: "src/assets/elements_images/grass.svg",
    color: "#63BC5A",
  },
  {
    type: "electric",
    type_pt: "Elétrico",
    src: "src/assets/elements_images/electric.svg",
    color: "#F4D23C",
  },
  {
    type: "psychic",
    type_pt: "Psíquico",
    src: "src/assets/elements_images/psychic.svg",
    color: "#FA7179",
  },
  {
    type: "ice",
    type_pt: "Gelo",
    src: "src/assets/elements_images/ice.svg",
    color: "#73CEC0",
  },
  {
    type: "dragon",
    type_pt: "Dragão",
    src: "src/assets/elements_images/dragon.svg",
    color: "#0B6DC3",
  },
  {
    type: "dark",
    type_pt: "Noturno",
    src: "src/assets/elements_images/dark.svg",
    color: "#5A5465",
  },
  {
    type: "fairy",
    type_pt: "Fada",
    src: "src/assets/elements_images/fairy.svg",
    color: "#EC8FE6",
  },
  { type: "unknown", type_pt: "Desconhecido", src: "", color: "#B7B7B7" },
  { type: "shadow", type_pt: "Sombra", src: "", color: "#333333" },
];
