export const pokemonsTypes = [
  { key: "normal", name: "Normal", color: "#A8A77A" },
  { key: "fighting", name: "Lutador", color: "#C22E28" },
  { key: "flying", name: "Voador", color: "#A98FF3" },
  { key: "poison", name: "Venenoso", color: "#A33EA1" },
  { key: "ground", name: "Terrestre", color: "#E2BF65" },
  { key: "rock", name: "Pedra", color: "#B6A136" },
  { key: "bug", name: "Inseto", color: "#A6B91A" },
  { key: "ghost", name: "Fantasma", color: "#735797" },
  { key: "steel", name: "Metálico", color: "#B7B7CE" },
  { key: "fire", name: "Fogo", color: "#EE8130" },
  { key: "water", name: "Água", color: "#6390F0" },
  { key: "grass", name: "Planta", color: "#7AC74C" },
  { key: "electric", name: "Elétrico", color: "#F7D02C" },
  { key: "psychic", name: "Psíquico", color: "#F95587" },
  { key: "ice", name: "Gelo", color: "#96D9D6" },
  { key: "dragon", name: "Dragão", color: "#6F35FC" },
  { key: "dark", name: "Noturno", color: "#705746" },
  { key: "fairy", name: "Fada", color: "#D685AD" },
  { key: "unknown", name: "Desconhecido", color: "#B7B7B7" },
  { key: "shadow", name: "Sombra", color: "#333333" },
];
