export const pokemonsTypes = [
  {
    type: "normal",
    type_pt: "Normal",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/normal.svg",
    color: "145, 154, 162",
  },
  {
    type: "fighting",
    type_pt: "Lutador",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/fighting.svg",
    color: "206, 65, 107",
  },
  {
    type: "flying",
    type_pt: "Voador",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/flying.svg",
    color: "137, 170, 227",
  },
  {
    type: "poison",
    type_pt: "Venenoso",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/poison.svg",
    color: "181, 103, 206",
  },
  {
    type: "ground",
    type_pt: "Terrestre",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/ground.svg",
    color: "217, 120, 69",
  },
  {
    type: "rock",
    type_pt: "Pedra",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/rock.svg",
    color: "197, 183, 140",
  },
  {
    type: "bug",
    type_pt: "Inseto",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/bug.svg",
    color: "145, 193, 47",
  },
  {
    type: "ghost",
    type_pt: "Fantasma",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/ghost.svg",
    color: "82, 105, 173",
  },
  {
    type: "steel",
    type_pt: "Metálico",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/steel.svg",
    color: "90, 142, 162",
  },
  {
    type: "fire",
    type_pt: "Fogo",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/fire.svg",
    color: "255, 157, 85",
  },
  {
    type: "water",
    type_pt: "Água",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/water.svg",
    color: "80, 144, 214",
  },
  {
    type: "grass",
    type_pt: "Planta",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/grass.svg",
    color: "99, 188, 90",
  },
  {
    type: "electric",
    type_pt: "Elétrico",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/electric.svg",
    color: "244, 210, 60",
  },
  {
    type: "psychic",
    type_pt: "Psíquico",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/psychic.svg",
    color: "250, 113, 121",
  },
  {
    type: "ice",
    type_pt: "Gelo",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/ice.svg",
    color: "115, 206, 192",
  },
  {
    type: "dragon",
    type_pt: "Dragão",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/dragon.svg",
    color: "11, 109, 195",
  },
  {
    type: "dark",
    type_pt: "Noturno",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/dark.svg",
    color: "90, 84, 101",
  },
  {
    type: "fairy",
    type_pt: "Fada",
    src: "https://raw.githubusercontent.com/carvalhaus/pokedex/main/src/assets/elements_images/fairy.svg",
    color: "236, 143, 230",
  },
  {
    type: "unknown",
    type_pt: "Desconhecido",
    src: "",
    color: "183, 183, 183",
  },
  { type: "shadow", type_pt: "Sombra", src: "", color: "51, 51, 51" },
];
